services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: together_dev
      POSTGRES_USER: together
      POSTGRES_PASSWORD: together
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
